server:
  port: 8081
    servlet:
      context-path: /weipinghui

spring:
  thymeleaf:
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/static/
    suffix: .html

  mvc:
    view:
      prefix: /
      suffix: .html


#映射静态资源
    static-path-pattern: /**

  resources:
    static-locations: classpath:/templates/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/upload






