server:
  port: 8081

spring:
  thymeleaf:
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/static/
    suffix: .html

  mvc:
    view:
      prefix: /
      suffix: .html


#映射静态资源
    static-path-pattern: /**

  resources:
    static-locations: classpath:/templates/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/upload
#
#  application:
#    name: weipinghuiHZweb
#
#eureka:
#  client:
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://localhost:6003/eureka #向这个注册
#      #Eureka服务器集群
#      #defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
#  instance:
#    instance-id: weipinghuiHZweb-8081
#    prefer-ip-address: true     #访问路径可以显示IP地址





