server:
  port: 8081

spring:
  mvc:
    view:
      prefix: /
      suffix: .html

#映射静态资源
    static-path-pattern: /**

  resources:
    static-locations: classpath:/templates/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/upload



#  redis:
#    database: 0
#    host: 192.168.44.128
#    port: 6379
#    password: 123456
#    timeout: 10s
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 5
#        min-idle: -1

  application:
    name: WEIPINGHUI-WEBHZ

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

feign:
  httpclient:
    connection-timeout: 30000

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:6003/eureka
      #Eureka服务器集群
      #defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
  instance:
    instance-id: myservice-consumer-8087
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: HZweb-8081
  company.name: www.cssl.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$





