server:
  port: 6003

eureka:
  server:
    enable-self-preservation: false   #禁用保护
    eviction-interval-timer-in-ms: 10000
  instance:
    hostname: localhost              #eureka服务端的实例名称(单机)
    #hostname: 106.52.15.109       #eureka服务端的实例名称(集群)
  client:
    register-with-eureka: false       #false表示不向注册中心注册自己。
    fetch-registry: false             #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://localhost:6003/eureka/       # 这个是别的服务要访问的地址 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      #defaultZone: http://eureka6622.com:6002/eureka/  #（集群）



