server:
  port: 30002
  servlet:
    context-path: /CZWafter

#数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///weipinhui
    username: root
    password: 123

#映射静态资源
    static-path-pattern: /**

  resources:
    static-locations: classpath:/templates/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/upload

mybatis:
  type-aliases-package: com.cssl.pojo
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  pageSizeZero: true

thymeleaf:
  encoding: UTF-8
  #开发时关闭缓存,不然没法看到实时页面
  cache: false
  prefix: classpath:/templates/  #默认
  suffix: .html                  #默认