server:
  port: 30001
#  servlet:
#    context-path: /CZWweb  #不要起名字否则微服务调用不到

#数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///weipinhui
    username: root
    password: 123

  application:
    name: microservice-czwconsumer

  redis:
    database: 0
    host: 192.168.220.135
    port: 6379
    password: 1
    timeout: 10s
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: -1
  mvc:
    view:
      prefix: /
      suffix: .html
#映射静态资源
    static-path-pattern: /**

  resources:
    static-locations: classpath:/templates/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/upload

  thymeleaf:
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templates/  #默认
    suffix: .html                  #默认

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:6003/eureka/
  instance:
    instance-id: microservice-czwconsumer-80
    prefer-ip-address: true     #访问路径可以显示IP地址

feign:
  httpclient:
    connection-timeout: 30000
  hystrix:
    enabled: true


mybatis:
  type-aliases-package: com.weip.pojo #这个可能
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  pageSizeZero: true




