server:
  port: 80
  servlet:
    context-path: /yemian

#数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///weipinhui
    username: root
    password: root

#映射静态资源
    static-path-pattern: /**

  resources:
    static-locations: classpath:/templates/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/upload

mybatis:
  type-aliases-package: com.cssl.pojo
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

thymeleaf:
  encoding: UTF-8
  #开发时关闭缓存,不然没法看到实时页面
  cache: false
  prefix: classpath:/templates/  #默认
  suffix: .html                  #默认

  eureka:
    client:
      register-with-eureka: true
      service-url:
        defaultZone: http://eureka6003.com:6003/eureka/
    instance:
      instance-id: weipinhuiMWXweb
      prefer-ip-address: true     #访问路径可以显示IP地址

  #注释后hystrix服务降级不可用
  feign:
    hystrix:
      enabled: true