server:
  port: 80

spring:
  thymeleaf:
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/static/
    suffix: .html

  #spring:
  application:
    name: weipinhuiMWXweb

  mvc:
    static-path-pattern: /**
  #修改默认的静态寻址资源目录
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  redis:
    database: 0
    host: 192.168.44.128
    port: 6379
    password: 123456
    timeout: 10s
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: -1

  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql:///weipinhui
      username: root
      password: root
      dbcp2:
        min-idle: 5
        initial-size: 5
        max-total: 5
        max-wait-millis: 200

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:6003/eureka/
  instance:
    instance-id: weipinhuiMWXweb-80
    prefer-ip-address: true     #访问路径可以显示IP地址
